---
- name: Build and push Docker image
  hosts: localhost
  tasks:
    - name: Build Docker image
      command: sudo docker build -t wonjune95/keduit:puple .
      args:
        chdir: "{{ workspace }}"
    - name: Push Docker image
      command: sudo docker push wonjune95/keduit:puple
