---
- name: Build and Push Docker image on Master
  hosts: master
  gather_facts: false
  tasks:
    - name: Download specific file from GitHub
      ansible.builtin.shell: wget https://raw.githubusercontent.com/wonjune95/jenkinsfile/main/index.html -O /var/lib/jenkins/workspace/wonjune/index.html


    - name: Log in to Docker Hub
      command: docker login -u wonjune95 -p dnjswns95!!
      no_log: true

    - name: Copy files from Jenkins workspace to Docker build context
      copy:
        src: /var/lib/jenkins/workspace/wonjune/
        dest: /root/portal/
        remote_src: no

    - name: Build Docker image
      command: docker build -t wonjune95/keduitlab:puple .
      args:
        chdir: /root/portal

    - name: Push Docker image to Docker Hub
      command: docker push wonjune95/keduitlab:puple

    - name: Deploy to Kubernetes
      command: kubectl create deploy web-puple --replicas=3 --port=80 --image=wonjune95/keduitlab:puple
      ignore_errors: yes

    - name: Expose Service on Kubernetes
      command: kubectl expose deploy web-puple --type=LoadBalancer --port=80 --target-port=80 --name=web-puple-svc
      ignore_errors: yes
