# playbook.yml
---
- name: Build and Push Docker image on Master
  hosts: master
  tasks:
    - name: Log in to Docker Hub
      command: docker login -u <your_dockerhub_username> -p <your_dockerhub_password>
      no_log: true

    - name: Build Docker image
      command: docker build -t wonjune95/keduit:puple .
      args:
        chdir: /root/portal

    - name: Push Docker image to Docker Hub
      command: docker push wonjune95/keduit:puple
