---
- name: Build and Push Docker image on Master
  hosts: master
  tasks:
    # PlayBook 복사하기
    - name: Copy Ansible Playbook to Master
      copy:
        src: /var/lib/jenkins/workspace/wonjunetest/playbook.yml  # Jenkins에서 뽑아올 경로
        dest: /root/jen/playbook.yml  # 복사해서 들어갈 경로

    # Deploy용 yml 복사하기
    - name: Copy Ansible Deploy to Master
      copy:
        src: /var/lib/jenkins/workspace/wonjunetest/testpod.yml  # Jenkins에서 뽑아올 경로
        dest: /root/jen/testpod.yml  # 복사해서 들어갈 경로
  
    # Docker 레지스트리에 로그인하기
    - name: Log in to Docker Registry
      command: docker login 211.183.3.199 -u admin -p test123  # 아이디 비밀번호 확인하기

    # Docker 이미지를  빌드하기
    - name: Build Docker image
      command: docker build -t wonjune:0913 .
      args:
        chdir: /root/jen/subject_option  # Dockerfile이 있는  경로

    # Docker 이미지를 태그하기
    - name: Tag Docker image
      command: docker tag wonjune:0913 211.183.3.199/wonjune/jang:0913

    # Docker 이미지를 레지스트리에 푸시하기
    - name: Push Docker image to Docker Registry
      command: docker push 211.183.3.199/wonjune/jang:0913

    # Kubernetes Deployment 적용
    - name: Apply Deployment
      command: kubectl apply -f /root/jen/testpod.yml