---
- name: Build and Push Docker image on Master
  hosts: master
  gather_facts: false
  tasks:    
    - name: Dockerfile
      copy:
        src: /var/lib/jenkins/workspace/wonjune/Dockerfile
        dest: /root
        
    - name: Index.html
      copy:
        src: /var/lib/jenkins/workspace/wonjune/index.html
        dest: /root
 
    - name: Log in to Docker Hub
      command: docker login -u wonjune95 -p dnjswns95!!

    - name: Docker build
      command: docker build -t wonjune95/keduitlab:purple /root

    - name: Docker Push
      command: docker push wonjune95/keduitlab:purple

    - name: Deploy to Kubernetes
      command: kubectl create deploy web-purple --replicas=3 --port=80 --image=wonjune95/keduitlab:purple

    - name: Expose Service on Kubernetes
      command: kubectl expose deploy web-purple --type=LoadBalancer --port=80 --target-port=80 --name=web-purple-svc
    
